[package]
name = "binlang"
version = "0.1.0"
authors = ["mchlf"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "0.22.3"
nom = "7.1.0"

